name: Build Amazon MSK CDK
on:
  push:
    branches: [ main, 'feature/**'  ]
  pull_request:
    branches: [ main, 'feature/**' ]
  workflow_dispatch:
jobs:
  secure-private-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: amazon-msk/cdk
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        working-directory: amazon-msk/cdk
        run: npm install
      - name: Run tests
        working-directory: amazon-msk/cdk
        run: npm run test

